commands:
  build:
    messages:
      cmd_started: "🚀 Build for #{pr_number} started."
      cmd_completed: "✅ Build completed: `ghcr.io/codeshelldev/secured-signal-api:{{image_tag}}`."

    workflow_file: pr-build.yml
    staff_only: true
