server:
  port: 8880

api:
  tokens:
  url:

messageAliases:
  [
    { alias: msg, score: 100 },
    { alias: content, score: 99 },
    { alias: description, score: 98 },
    { alias: text, score: 20 },
    { alias: body, score: 15 },
    { alias: summary, score: 10 },
    { alias: details, score: 9 },
    { alias: payload, score: 2 },
    { alias: data, score: 1 },
  ]

blockedEndpoints:
  - /v1/about
  - /v1/configuration
  - /v1/devices
  - /v1/register
  - /v1/unregister
  - /v1/qrcodelink
  - /v1/accounts
  - /v1/contacts
