server:
  port: 8880

logLevel: info

settings:
  variables:
    recipients: ${RECIPIENTS}
    number: ${NUMBER}

  blockedEndpoints:
    - /v1/about
    - /v1/configuration
    - /v1/devices
    - /v1/register
    - /v1/unregister
    - /v1/qrcodelink
    - /v1/accounts
    - /v1/contacts
