# Example Config (all configurations shown)

api:
  port: 8880
  url: http://signal-api:8080
  tokens: [token1, token2]

logLevel: INFO

settings:
  variables:
    number: "+123400001"
    recipients: [+123400002, group.id, user.id]

  messageAliases: [{ alias: "msg", score: 100 }]

  blockedEndpoints:
    - /v1/about
  allowedEndpoints:
    - /v2/send
