# Example Config (all configurations shown)

api:
  port: 8880
  url: http://signal-api:8080
  tokens: [token1, token2]

logLevel: info

settings:
  messageTemplate: |
    You've got a Notification:
    {{@message}} 
    At {{@data.timestamp}} on {{@data.date}}.
    Send using {{.NUMBER}}.

  variables:
    number: "+123400001"
    recipients: ["+123400002", "group.id", "user.id"]

  dataAliases: 
    "@message": [{ alias: "msg", score: 100 }]

  blockedEndpoints:
    - /v1/about
  allowedEndpoints:
    - /v2/send
