name: Update Contributing

on:
  push:
    branches:
      - docs
    paths:
      - .github/templates/CONTRIBUTING.template.md
  workflow_dispatch:

jobs:
  contributing:
    uses: codeshelldev/gh-actions/.github/workflows/templating.yml@main
    name: Contributing
    with:
      template: ".github/templates/CONTRIBUTING.template.md"
      output: CONTRIBUTING.md
      output-branch: docs
      pr-title: "Automated Docs Contributing Update"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
