name: Update Contributing

on:
  push:
    paths:
      - .github/templates/CONTRIBUTING.template.md
  workflow_dispatch:

jobs:
  contributing:
    uses: codeshelldev/gh-actions/.github/workflows/templating.yml@main
    name: Readme
    with:
      template: .github/templates/CONTRIBUTING.template.md
      output: CONTRIBUTING.md
      output-branch: docs
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
