name: Update Documentation

on:
  workflow_dispatch:

jobs:
  docs:
    name: Template Docs
    runs-on: ubuntu-latest

    steps:
      - name: Fail
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "❌ This workflow cannot be run from the main branch."
          echo "Please pin to a release, use another branch or commit SHA instead of @main."
          exit 1
