name: Cleanup Images

on:
  workflow_run:
    workflows: ["Build & Push Image"]
    types:
      - completed

  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    name: Images

    steps:
      - uses: codeshelldev/gh-actions/ghcr-cleanup@v1
        with:
          image: ${{ github.repository }}
          registry: ghcr.io
          token: ${{ secrets.GH_PCKG_TOKEN }}
          delete-tags: '^(?:pr-\d+-\d+|ci-[A-Za-z0-9._-]+-\d+|[A-Za-z0-9._-]+-dev\d)$'
          older-than: 15 days
