name: Cleanup Images

on:
  workflow_run:
    workflows:
      [
        "Build & Push Image",
        "Build & Push Dev Image",
        "Build & Push Image via Command",
      ]
    types:
      - completed
  workflow_dispatch:

jobs:
  update:
    uses: codeshelldev/gh-actions/.github/workflows/image-cleanup.yml@main
    name: Images
    with:
      registry: ghcr.io
      cleanup-stales: pr-[0-9]+-[0-9]+,ci-[a-zA-Z0-9._-]+-[0-9]+,[a-zA-Z0-9._-]+-dev-[0-9]+
      stale-threshold: 15 days
    secrets:
      GH_PCKG_TOKEN: ${{ secrets.GH_PCKG_TOKEN }}
